export enum JobState {
    UPLOADED = "UPLOADED",
    OCR_PROCESSING = "OCR_PROCESSING",
    OCR_FAILED = "OCR_FAILED",
    FREE_SUMMARY_GENERATING = "FREE_SUMMARY_GENERATING",
    FREE_SUMMARY_COMPLETE = "FREE_SUMMARY_COMPLETE",
    AWAITING_PAYMENT = "AWAITING_PAYMENT",
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
    PAID_BREAKDOWN_GENERATING = "PAID_BREAKDOWN_GENERATING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    REFUNDED = "REFUNDED",
}
